In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Loan payments data.csv")
data.head()

Loan_ID loan_status  Principal  terms effective_date   due_date  \
0  xqd20166231     PAIDOFF       1000     30       9/8/2016  10/7/2016   
1  xqd20168902     PAIDOFF       1000     30       9/8/2016  10/7/2016   
2  xqd20160003     PAIDOFF       1000     30       9/8/2016  10/7/2016   
3  xqd20160004     PAIDOFF       1000     15       9/8/2016  9/22/2016   
4  xqd20160005     PAIDOFF       1000     30       9/9/2016  10/8/2016   

     paid_off_time  past_due_days  age             education  Gender  
0  9/14/2016 19:31            NaN   45  High School or Below    male  
1   10/7/2016 9:00            NaN   50              Bechalor  female  
2  9/25/2016 16:58            NaN   33              Bechalor  female  
3  9/22/2016 20:00            NaN   27               college    male  
4  9/23/2016 21:36            NaN   28               college  female

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Loan_ID         500 non-null    object 
 1   loan_status     500 non-null    object 
 2   Principal       500 non-null    int64  
 3   terms           500 non-null    int64  
 4   effective_date  500 non-null    object 
 5   due_date        500 non-null    object 
 6   paid_off_time   400 non-null    object 
 7   past_due_days   200 non-null    float64
 8   age             500 non-null    int64  
 9   education       500 non-null    object 
 10  Gender          500 non-null    object 
dtypes: float64(1), int64(3), object(7)
memory usage: 43.1+ KB


In [4]:
data['loan_status'].value_counts()

PAIDOFF               300
COLLECTION            100
COLLECTION_PAIDOFF    100
Name: loan_status, dtype: int64

In [5]:
data['loan_status']=np.where(data['loan_status']=='PAIDOFF', 0, np.where(data['loan_status']=='COLLECTION', 1, 2))
data['loan_status'].value_counts()

0    300
2    100
1    100
Name: loan_status, dtype: int64

In [7]:
data['education'].value_counts()

college                 220
High School or Below    209
Bechalor                 67
Master or Above           4
Name: education, dtype: int64

In [9]:
data['education']=np.where(data['education']=='High School or Below', 0, np.where(data['education']=='college', 1, np.where(data['education']=='Bechalor', 2, 3)))
data['education'].value_counts()

1    220
0    209
2     67
3      4
Name: education, dtype: int64

In [11]:
data['Gender'].value_counts()

male      423
female     77
Name: Gender, dtype: int64

In [12]:
data['Gender']=np.where(data['Gender']=='male', 0, 1)
data['Gender'].value_counts()

0    423
1     77
Name: Gender, dtype: int64

In [23]:
data['past_due_days'].value_counts()

59.0    40
74.0    25
2.0     22
1.0     18
3.0     14
60.0    13
4.0      8
75.0     7
29.0     7
5.0      5
27.0     3
76.0     3
7.0      3
44.0     3
14.0     3
28.0     2
58.0     2
13.0     2
61.0     2
12.0     2
25.0     2
24.0     2
6.0      2
56.0     1
73.0     1
36.0     1
23.0     1
38.0     1
19.0     1
52.0     1
51.0     1
9.0      1
8.0      1
Name: past_due_days, dtype: int64

In [24]:
data['past_due_days']=np.where(data['past_due_days'].isnull(), 0.0, data['past_due_days'])

In [14]:
data.columns

Index(['Loan_ID', 'loan_status', 'Principal', 'terms', 'effective_date',
       'due_date', 'paid_off_time', 'past_due_days', 'age', 'education',
       'Gender'],
      dtype='object')

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Loan_ID         500 non-null    object 
 1   loan_status     500 non-null    int32  
 2   Principal       500 non-null    int64  
 3   terms           500 non-null    int64  
 4   effective_date  500 non-null    object 
 5   due_date        500 non-null    object 
 6   paid_off_time   400 non-null    object 
 7   past_due_days   500 non-null    float64
 8   age             500 non-null    int64  
 9   education       500 non-null    int32  
 10  Gender          500 non-null    int32  
dtypes: float64(1), int32(3), int64(3), object(4)
memory usage: 37.2+ KB


In [29]:
X=data[['Principal', 'terms', 'past_due_days', 'age', 'education', 'Gender']]
y=data[['loan_status']]

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=42)

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [32]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

<ipython-input-32-6bcdfb52040f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_scaled_train, y_train)


1.0

In [33]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
print(confusion_train)

[[212   0   0]
 [  0  69   0]
 [  0   0  69]]


In [34]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.98

In [35]:
confusion_test=confusion_matrix(y_test, pred_test)
confusion_test

array([[88,  0,  0],
       [ 0, 31,  0],
       [ 0,  3, 28]], dtype=int64)

In [37]:
pred_test=np.where(pred_test==0, 'PAIDOFF', np.where(pred_test==1, 'COLLECTION', 'COLLECTION_PAIDOFF'))
pred_test

array(['COLLECTION', 'PAIDOFF', 'COLLECTION', 'PAIDOFF', 'PAIDOFF',
       'COLLECTION', 'COLLECTION', 'PAIDOFF', 'PAIDOFF',
       'COLLECTION_PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'COLLECTION_PAIDOFF',
       'PAIDOFF', 'COLLECTION', 'COLLECTION', 'COLLECTION_PAIDOFF',
       'PAIDOFF', 'COLLECTION', 'COLLECTION', 'COLLECTION_PAIDOFF',
       'COLLECTION', 'PAIDOFF', 'COLLECTION', 'PAIDOFF',
       'COLLECTION_PAIDOFF', 'COLLECTION_PAIDOFF', 'PAIDOFF', 'PAIDOFF',
       'COLLECTION', 'COLLECTION_PAIDOFF', 'COLLECTION',
       'COLLECTION_PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'COLLECTION',
       'COLLECTION_PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF',
       'COLLECTION', 'PAIDOFF', 'COLLECTION_PAIDOFF', 'PAIDOFF',
       'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'COLLECTION_PAIDOFF',
       'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'COLLECTION_PAIDOFF',
       'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF',
       'COLLECTION_PAIDOFF', 'PAIDOFF', 'COLLECTION',
       'COLLEC

In [43]:
pred_test=pd.DataFrame({'loan_status':pred_test})
pred_test

loan_status
0            COLLECTION
1               PAIDOFF
2            COLLECTION
3               PAIDOFF
4               PAIDOFF
..                  ...
145             PAIDOFF
146             PAIDOFF
147             PAIDOFF
148             PAIDOFF
149  COLLECTION_PAIDOFF

[150 rows x 1 columns]

In [45]:
pred_test.to_csv("3-7-14.csv")